apiVersion: v1
kind: Pod
metadata:
  name: sample01
spec:
  containers:
    - name: httpd
      image: raghudevops25/httpd:v1
      ports:
        - containerPort: 80
          hostPort: 80
  nodeSelector:
      ENV: DEV 
