---
apiVersion: v1
kind: Namespace
metadata:
  name: test
...
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myhttpd-rc2
  namespace: test
spec:
  replicas: 2
  template:
    metadata:
      name: myhttpd-rc2
      labels:
        app: myhttpd2
    spec:
      containers:
      - name: httpd
        image: raghudevops25/httpd:v2
        ports:
        - containerPort: 80
...
---
kind: Service
apiVersion: v1
metadata:
  name: myhttpd-rc2-svc
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: myhttpd2
  ports:
  - port: 80
...
