apiVersion: v1
kind: Pod
metadata:
  name: vol-gce
spec:
  containers:
  - name: httpd
    image: raghudevops25/httpd:v2
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /var/www/html
      name: httpd-volume
  volumes:
  - name: httpd-volume
    persistentVolumeClaim:
          claimName: httpd-volume
  

