apiVersion: v1
kind: Pod
metadata:
  name: vol-nfs
spec:
  containers:
  - name: httpd
    image: raghudevops25/httpd:v2
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /var/www/html
      name: httpd-volume
  volumes:
  - name: httpd-volume
    nfs:
      server: 10.142.0.17
      path: "/data"
  

