apiVersion: v1
kind: ReplicationController
metadata:
  name: myhttpd-rc1
spec:
  replicas: 2
  template:
    metadata:
      name: myhttpd-rc1
      labels:
        app: myhttpd
    spec:
      containers:
      - name: httpd
        image: raghudevops25/httpd:v2
        ports:
        - containerPort: 80
