apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat
spec:
  replicas: 1
  template:
    metadata:
      name: mytomcat-rc1
      labels:
        app: mytomcat
    spec:
      containers:
      - name: httpd
        image: raghudevops25/tomcat
        ports:
        - containerPort: 8080
