apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2018-03-08T02:44:58Z","reason":"ReadyForNewScale","message":"the
        last scale time was sufficiently old as to warrant a new scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2018-03-08T02:44:58Z","reason":"ValidMetricFound","message":"the
        HPA was able to succesfully calculate a replica count from cpu resource utilization
        (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2018-03-08T02:44:58Z","reason":"TooFewReplicas","message":"the
        desired replica count was less than the minimum replica count"}]'
      autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
    creationTimestamp: 2018-03-08T02:44:28Z
    name: myhttpd-deploy1
    namespace: default
    resourceVersion: "131160"
    selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/myhttpd-deploy1
    uid: 9f4034b5-227a-11e8-997f-42010a8002a8
  spec:
    maxReplicas: 15
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: myhttpd-deploy1
    targetCPUUtilizationPercentage: 10
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 4
    desiredReplicas: 4
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
